### ISSUE TITLE
About MatchingNet

### ISSUE THREAD

**Issue by LoveMiki** [Tsingularity/FRN#10]
Dear authors
Sorry to bother you. In your paper, i notice that you re-implement MatchingNet using the pre-trained backbone.
Could you kindly provide the code of your implementation on MatchingNet? I followed the code from "A closer look at few-shot", and used the pre-trained model from your code. However, it seems that the model learns nothing and I cannot reproduce the results.

Thank you in advance.

**Comment by Tsingularity** [comment]
We actually didn't re-implement matchnet so I am afraid I cannot help you much with this. As stated in the paper table 3-6, we only re-implement CTX, ProtoNet and DSN. The matchnet performance numbers are from the papers cited in each table, mainly FEAT, DeepEMD and Closer-look-at.
