### ISSUE TITLE
Issue on regularization

### ISSUE THREAD

**Issue by ccl163** [Tsingularity/FRN#12]
Hi, thank you for this enlightening work! 

And sorry for bothering if this is a basic question, but I am new to this field and I would like to know why the support features can span the feature space when kr > d, as stated in section 3.2 in your paper. Also what does it mean by "span the feature space"?

> If kr > d, reconstruction may become trivial, as the support features can span the feature space. Conversely, reconstruction is difficult when d > kr

If the explanation may be lengthy, could you recommend some keywords I could use to find related materials so I can learn it myself?Thank you in advance!

**Comment by ccl163** [comment]
Thank you so much for the quick response! And your clear explaination really helps me a lot!

I have another question: if I'm understanding correctly, in terms of the number of points in space, this applies not only to the reconstruction problem/feature map ridge regression here, but also other regression problems?

So it is still pretty easy to find the matrix W where W·Sc ≈ Q in most cases, as long as there is no regularization.  It is just that, when d > kr, the reconstruction featrure map Qc_hat might be numerically inaccurate compared to the original Q, even if the support and query images are from the same class. Thus the reconstruction error will be large and the calculated distance is not discriminatory enough to solve few shot learning problems.

I always understood `reconstruction is difficult when d > kr` as `finding a matrix W where W·Sc ≈ Q  is difficult when kr > d`, which is why I have been confused about this section.

Please point out any mistake if I am wrong. Thank you in advance!

**Comment by daviswer** [comment]
Nope, your current understanding is entirely correct! It's not that calculating matrix W is difficult, it's that forming a meaningful/discriminative reconstruction is difficult. Happy I could help, closing the issue for now.
