### ISSUE TITLE
Can authors open source the visualization part of the code?

### ISSUE THREAD

**Issue by wangpangpang12** [Tsingularity/FRN#14]

**Comment by daviswer** [comment]
Hi, thanks for the interest and sorry for the late response. Are you referring to the image reconstruction figures (Fig3 and supplementary)? We're not planning to add this to the repo, as it's not a major component of FRN or its evaluation, but as a one-off I could probably share a notebook with most of the visualization code for CUB. There'd be a laundry list of disclaimers - it's old sandbox code, so it's unclean, out of date, and no guarantees on quality, and it might not be directly plug and play with the official, sanitized FRN implementation here. And if issues arise, I can't promise any support as I graduated two years ago. But if you want it, let me know and I can throw it together

**Comment by wangpangpang12** [comment]
Thank you very much for your reply! If it is convenient, please upload the  image reconstruction figures (Fig3 and supplementary) relevant code. Thanks again!

**Comment by wangpangpang12** [comment]
Hello author, my email is mrwangmy12@163.com, if it is convenient for you, you can also share the visual code via email. I'm sorry to bother you again

**Comment by daviswer** [comment]
Hi, sorry for my (again) delayed response - for whatever reason I didn't get any notification emails when you responded, and I hadn't been actively monitoring this page. I'll email you a notebook shortly!

**Comment by daviswer** [comment]
Sent! Hope it's helpful to you.

**Comment by sausage0611** [comment]
Dear author, hello! I'm sorry to disturb you, but I would also like to have a copy of the same visualization code. If it's convenient for you, could you please send it to me? my email is meiyinhu@email.ncu.edu.cn. I'm sorry to bother you.
