### ISSUE TITLE
Some data set links failed

### ISSUE THREAD

**Issue by WJLHYML** [Tsingularity/FRN#15]
Dear author, hello. I noticed that some of the data set links you provide in the readme file are not accessible (e.g. tired-imagenet), is it possible to ask you to provide a new link? Thank you for your help.

**Comment by Tsingularity** [comment]
Hi, thank you for your interest in our work!

Yeah, looks like some of the original dataset google drive link is expired, and to be honest, I also don't know what their updated link would be. If you find any, feel free to make a pull request.

Meanwhile, here're the post-processed few-shot [datasets](https://drive.google.com/drive/u/1/folders/1gHt-Ynku6Yc3mz6aKVTppIfNmzML1sNG) used in our experiments. See instructions [here](https://github.com/Tsingularity/FRN/blob/main/README.md?plain=1#L45).

Hope this helps!

**Comment by WJLHYML** [comment]
Thank you very much for your help.
