### ISSUE TITLE
Are drop blocks used indeed?

### ISSUE THREAD

**Issue by dahyun-kang** [Tsingularity/FRN#2]
Hello,

Thank you for your interesting work! 😃
According to the your arxiv paper page 12, you stated that you used drop blocks.

But the code base never leads me into the dropblock forwarding path. The code below never runs:
https://github.com/Tsingularity/FRN/blob/28aaa5c917645b34ac40f099808eb177e29e06c2/models/backbones/ResNet.py#L119-L126

possibily because the initial drop-out rate is set to 0:
https://github.com/Tsingularity/FRN/blob/28aaa5c917645b34ac40f099808eb177e29e06c2/models/backbones/ResNet.py#L192-L196

I hope it is a mistake on either the supplementary matarials or the code (or me 😉).
Congraturations and I hope you see you soon in CVPR'21!

Sincerely,
Dahyun

**Comment by Tsingularity** [comment]
Hi Dahyun,

Thanks a lot for your interest in our work, and for bringing this to our attention!

- Is drop-block used in the experiments or not?
The answer is no. After double-checking both the public FRN repo and our own working codebase where we got the few-shot numbers for the paper, we found that the issue you mentioned actually exists in all our implemented methods. The drop_rate argument never gets into the ResNet initialization, therefore the drop_rate is always set to the default value 0. So the statement in the supplementary material is incorrect. Thanks a lot for spotting this inconsistency between our paper and code! And we apologize for the mistake. We’ll fix it and update the arxiv paper later.

- How did this happen?
There are three papers and repositories we referred to when implementing our ResNet-12 backbone: FEAT ([code](https://github.com/Sha-Lab/FEAT)), RFS ([code](https://github.com/WangYueFt/rfs)) and DeepEMD ([code](https://github.com/icoz69/DeepEMD)). Their implementations are basically the same with only a few small differences.
In FEAT ([code snippet](https://github.com/Sha-Lab/FEAT/blob/master/model/networks/res12.py#L73)), the default value for drop_rate is set to be 0.1. In RFS ([code snippet 1](https://github.com/WangYueFt/rfs/blob/master/models/resnet.py#L151), [code snippet 2](https://github.com/WangYueFt/rfs/blob/f8c837ba93c62dd0ac68a2f4019c619aa86b8421/models/util.py#L16)), the default value is 0 but the argument has been manually set to 0.1 when creating models. DeepEMD ([code snippet](https://github.com/icoz69/DeepEMD/blob/master/Models/models/resnet.py#L67)) has a drop_rate defaulting to 0 but no implementation for nonzero values.
When we merged these three implementations into one concise ResNet-12 code, we forgot to verify the drop_rate argument and didn’t notice this mistake either before or after our experiments were done.

- Does this issue affect the paper’s conclusion, i.e., FRN’s effectiveness, and should the audience worry about it?
As mentioned above, all our implemented models (ProtoNet, CTX, DSN, FRN) use the same ResNet-12 backbone so the comparison is still fair. Also, many competitive few-shot papers (including DeepEMD and [meta-baseline](https://arxiv.org/pdf/2003.04390.pdf)) don’t include drop blocks in their implementation. 
In addition, based on the ablation study (table 4) in MetaOptNet [paper](https://arxiv.org/pdf/1904.03758.pdf), adding DropBlock could further boost the performance by about 1 percentage point. As a regularization method, DropBlock should be able to prevent overfitting and improve models’ generalization ability in general. So there’s a high probability that correctly implementing drop block in FRN will produce even better performance than reported in our paper.
Therefore we think this issue shouldn’t affect our paper’s conclusion at all and people shouldn’t need to worry about it. 

- So what’s next?
We’ve updated the code to allow for dropblock usage but set the default drop_rate to 0. We’ll update either the code or paper to be consistent once we know the precise impact of dropblock on our model(s). Based on a couple preliminary runs on DSN and CTX this impact appears to be quite small (within 0.5 percentage points of reported numbers). Meanwhile, feel free to try it yourself if you are also interested and available! And please let us know if you get the new numbers or if there’s anything else we can help with.

Thanks again for your great feedback!

**Comment by dahyun-kang** [comment]
Thank you for the prompt and comprehensive reply. :+1: 
I hope you have a great day. 

Closing this issue.
