### ISSUE TITLE
Performance on CUB

### ISSUE THREAD

**Issue by huangxilang901** [Tsingularity/FRN#5]
Thanks for sharing the codes and your excellent work.

In Table 3, I notice that ProtoNet achieves 81.50 with pre-training and 83.88 under your implementation using the basic Conv-4 backbone. Then, in 9.1, I find that you said "Conv-4 are trained with 20-way 5-shot for 5 shot model, and 30-way 1-shot for 1-shot model". 
So, the accuracy of 83.88 under your implementation is trained from scratch using the above settings with SGD? Did you implement ProtoNet using the general setting (e.g., 5-way 5-shot and 1-shot)? 

Sorry to bother you and thank you in advance.

**Comment by Tsingularity** [comment]
Yes, in the main CUB table, we don't do pre-training for our own implemented ProtoNet model. And you should be able to reproduce the numbers using our released code.

I didn't train with 5-way 5/1-shot episodes on this particular codebase, but feel free to give it a try! And also feel free to let us know if there's anything we can help with.

**Comment by Tsingularity** [comment]
closing this for now. feel free to re-open it if you need more help.
