### ISSUE TITLE
How to change the batch_size

### ISSUE THREAD

**Issue by jpzhai** [Tsingularity/FRN#9]
Hello, I found that the memory occupied by the program is very small, but there is no way to change the batch_size

**Comment by Tsingularity** [comment]
u can change the batch size or episode size by passing different cmd [args](https://github.com/Tsingularity/FRN/blob/main/trainers/trainer.py#L35). Here, "batch_size" means the one during pre-training. During meta-training, the episode size is actually controlled by "train_way", "train_shot" and "test_shot".

**Comment by Tsingularity** [comment]
closing this for now. feel free to re-open it if you need more help.
